version: "3.8"

volumes:
    # volumeはホストにコピー or 表示させないもの
    #バイナリファイル（node_module）など、OS依存があるもの

    # node_moduleを入れるvolume
    vue-cli-node-volume:
services:
  front:
    container_name: "samplefront"
    build: ./frontend/docker
    environment:
      TZ: 'Asia/Tokyo'
      NODE_ENV: 'development'
    ports:
        - "8080:8080"
    # restart: always
    volumes:
        #node_moduleを入れるボリューム
        - vue-cli-node-volume:/app/vue-app/node_modules
        #コンテナ内の指定ディレクトリをホスト側と同期
        - ./frontend/app:/app
    stdin_open: true
    tty: true
  api:
    links:
      - db
    container_name: "sampleapi"
    build: ./backend/docker/api
    env_file:
      - .env
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "8000:8000"
    volumes:
    - ./backend/app:/usr/src/server
    networks:
      - local-net
  db:
    container_name: "sampledb"
    build: ./backend/docker/mysql
    restart: always
    tty: true
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./backend/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./backend/docker/mysql/persistent/logs:/var/log/mysql
      - ./backend/docker/mysql/persistent/data:/var/lib/mysql
    networks:
      - local-net
networks:
  local-net:
    driver: bridge
