version: "3.3"

services:
  db:
    container_name: "db"
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.
      - ./log/mysql:/var/log/mysql
    networks:
      - local-net

  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    env_file:
      - .env
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "8000:8000"
    volumes:
    #   - ./src:/usr/src/server
    - ./src/app:/usr/src/server
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
